export type CommandCatalogEntry = {
  /**
   * CLI command names track daemon compatibility migration. Namespaced entries
   * track runtime router/API commands that are available independently.
   */
  command: string;
  category:
    | 'portable-runtime'
    | 'backend-admin'
    | 'transport-session'
    | 'environment'
    | 'capability-gated';
  status: 'implemented' | 'planned';
};

export const commandCatalog: readonly CommandCatalogEntry[] = [
  { command: 'screenshot', category: 'portable-runtime', status: 'implemented' },
  { command: 'diff screenshot', category: 'portable-runtime', status: 'implemented' },
  { command: 'snapshot', category: 'portable-runtime', status: 'implemented' },
  { command: 'diff snapshot', category: 'portable-runtime', status: 'implemented' },
  { command: 'find read-only', category: 'portable-runtime', status: 'implemented' },
  { command: 'get', category: 'portable-runtime', status: 'implemented' },
  { command: 'is', category: 'portable-runtime', status: 'implemented' },
  { command: 'wait', category: 'portable-runtime', status: 'implemented' },
  { command: 'alert', category: 'portable-runtime', status: 'planned' },
  { command: 'click', category: 'portable-runtime', status: 'implemented' },
  { command: 'press', category: 'portable-runtime', status: 'implemented' },
  { command: 'fill', category: 'portable-runtime', status: 'implemented' },
  { command: 'longpress', category: 'portable-runtime', status: 'planned' },
  { command: 'swipe', category: 'portable-runtime', status: 'planned' },
  { command: 'focus', category: 'portable-runtime', status: 'planned' },
  { command: 'type', category: 'portable-runtime', status: 'implemented' },
  { command: 'scroll', category: 'portable-runtime', status: 'planned' },
  { command: 'pinch', category: 'portable-runtime', status: 'planned' },
  { command: 'interactions.focus', category: 'portable-runtime', status: 'implemented' },
  { command: 'interactions.longPress', category: 'portable-runtime', status: 'implemented' },
  { command: 'interactions.swipe', category: 'portable-runtime', status: 'implemented' },
  { command: 'interactions.scroll', category: 'portable-runtime', status: 'implemented' },
  { command: 'interactions.pinch', category: 'portable-runtime', status: 'implemented' },
  { command: 'open', category: 'portable-runtime', status: 'planned' },
  { command: 'close', category: 'portable-runtime', status: 'planned' },
  { command: 'apps', category: 'portable-runtime', status: 'planned' },
  { command: 'appstate', category: 'portable-runtime', status: 'planned' },
  { command: 'apps.open', category: 'portable-runtime', status: 'implemented' },
  { command: 'apps.close', category: 'portable-runtime', status: 'implemented' },
  { command: 'apps.list', category: 'portable-runtime', status: 'implemented' },
  { command: 'apps.state', category: 'portable-runtime', status: 'implemented' },
  { command: 'apps.push', category: 'portable-runtime', status: 'implemented' },
  { command: 'apps.triggerEvent', category: 'portable-runtime', status: 'implemented' },
  { command: 'back', category: 'portable-runtime', status: 'planned' },
  { command: 'home', category: 'portable-runtime', status: 'planned' },
  { command: 'rotate', category: 'portable-runtime', status: 'planned' },
  { command: 'app-switcher', category: 'portable-runtime', status: 'planned' },
  { command: 'keyboard', category: 'portable-runtime', status: 'planned' },
  { command: 'clipboard', category: 'portable-runtime', status: 'planned' },
  { command: 'settings', category: 'portable-runtime', status: 'planned' },
  { command: 'system.back', category: 'portable-runtime', status: 'implemented' },
  { command: 'system.home', category: 'portable-runtime', status: 'implemented' },
  { command: 'system.rotate', category: 'portable-runtime', status: 'implemented' },
  { command: 'system.appSwitcher', category: 'portable-runtime', status: 'implemented' },
  { command: 'system.keyboard', category: 'portable-runtime', status: 'implemented' },
  { command: 'system.clipboard', category: 'portable-runtime', status: 'implemented' },
  { command: 'system.settings', category: 'portable-runtime', status: 'implemented' },
  { command: 'system.alert', category: 'portable-runtime', status: 'implemented' },
  { command: 'push', category: 'portable-runtime', status: 'planned' },
  { command: 'trigger-app-event', category: 'portable-runtime', status: 'planned' },
  { command: 'devices', category: 'backend-admin', status: 'implemented' },
  { command: 'boot', category: 'backend-admin', status: 'implemented' },
  { command: 'ensure-simulator', category: 'backend-admin', status: 'implemented' },
  { command: 'install', category: 'backend-admin', status: 'implemented' },
  { command: 'reinstall', category: 'backend-admin', status: 'implemented' },
  { command: 'install-from-source', category: 'backend-admin', status: 'implemented' },
  { command: 'admin.devices', category: 'backend-admin', status: 'implemented' },
  { command: 'admin.boot', category: 'backend-admin', status: 'implemented' },
  { command: 'admin.ensureSimulator', category: 'backend-admin', status: 'implemented' },
  { command: 'admin.install', category: 'backend-admin', status: 'implemented' },
  { command: 'admin.reinstall', category: 'backend-admin', status: 'implemented' },
  { command: 'admin.installFromSource', category: 'backend-admin', status: 'implemented' },
  { command: 'session', category: 'transport-session', status: 'planned' },
  { command: 'connect', category: 'environment', status: 'planned' },
  { command: 'disconnect', category: 'environment', status: 'planned' },
  { command: 'connection', category: 'environment', status: 'planned' },
  { command: 'metro', category: 'environment', status: 'planned' },
  { command: 'record', category: 'capability-gated', status: 'implemented' },
  { command: 'trace', category: 'capability-gated', status: 'implemented' },
  { command: 'replay', category: 'capability-gated', status: 'implemented' },
  { command: 'test', category: 'capability-gated', status: 'implemented' },
  { command: 'batch', category: 'capability-gated', status: 'implemented' },
  { command: 'logs', category: 'capability-gated', status: 'planned' },
  { command: 'network', category: 'capability-gated', status: 'planned' },
  { command: 'perf', category: 'capability-gated', status: 'planned' },
];
