import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  buildCommandUsageText,
  getCliCommandNames,
  getCommandSchema,
  getFlagDefinitions,
  getSchemaCapabilityKeys,
} from '../src/utils/command-schema.ts';
import { isCommandSupportedOnDevice } from '../src/core/capabilities.ts';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(SCRIPT_DIR, '..');
const KNOWLEDGE_DIR = path.join(ROOT_DIR, 'knowledge');
const GENERATED_HEADER = '<!-- Generated by `pnpm kb:build`. Do not edit manually. -->';

const COMMAND_ALIASES = {
  longpress: ['long-press'],
  perf: ['metrics'],
};

const COMMAND_NOTES = {
  back: ['`back --in-app` is the explicit alias for the default app-owned behavior.'],
  diff: ['`snapshot --diff` routes to `diff snapshot`.'],
  network: ['`network log` is an alias for `network dump`.'],
};

const SAMPLE_DEVICES = [
  {
    key: 'iosSimulator',
    label: 'iOS sim',
    device: {
      id: 'ios-sim-mobile',
      kind: 'simulator',
      name: 'iPhone Simulator',
      platform: 'ios',
      target: 'mobile',
    },
  },
  {
    key: 'iosDevice',
    label: 'iOS device',
    device: {
      id: 'ios-device-mobile',
      kind: 'device',
      name: 'iPhone',
      platform: 'ios',
      target: 'mobile',
    },
  },
  {
    key: 'tvSimulator',
    label: 'tvOS sim',
    device: {
      id: 'tvos-sim',
      kind: 'simulator',
      name: 'Apple TV Simulator',
      platform: 'ios',
      target: 'tv',
    },
  },
  {
    key: 'macosDesktop',
    label: 'macOS',
    device: {
      id: 'macos-desktop',
      kind: 'device',
      name: 'Mac',
      platform: 'macos',
      target: 'desktop',
    },
  },
  {
    key: 'androidEmulator',
    label: 'Android emu',
    device: {
      id: 'android-emu-mobile',
      kind: 'emulator',
      name: 'Android Emulator',
      platform: 'android',
      target: 'mobile',
    },
  },
  {
    key: 'androidDevice',
    label: 'Android device',
    device: {
      id: 'android-device-mobile',
      kind: 'device',
      name: 'Android Phone',
      platform: 'android',
      target: 'mobile',
    },
  },
  {
    key: 'androidTv',
    label: 'Android TV',
    device: {
      id: 'android-emu-tv',
      kind: 'emulator',
      name: 'Android TV Emulator',
      platform: 'android',
      target: 'tv',
    },
  },
];

const FAMILY_DEFINITIONS = [
  {
    name: 'session',
    commands: [
      'app-switcher',
      'appstate',
      'apps',
      'batch',
      'boot',
      'close',
      'devices',
      'ensure-simulator',
      'home',
      'install',
      'install-from-source',
      'logs',
      'metro',
      'network',
      'open',
      'perf',
      'push',
      'reinstall',
      'replay',
      'session',
      'test',
    ],
    primarySources: [
      'src/daemon/handlers/session.ts',
      'src/daemon/session-store.ts',
      'src/daemon/handlers/__tests__/session.test.ts',
    ],
    docs: [
      'website/docs/docs/commands.md',
      'website/docs/docs/replay-e2e.md',
      'skills/agent-device/SKILL.md',
      'skills/agent-device/references/bootstrap-install.md',
    ],
  },
  {
    name: 'interaction',
    commands: [
      'back',
      'click',
      'fill',
      'focus',
      'get',
      'is',
      'longpress',
      'pinch',
      'press',
      'scroll',
      'scrollintoview',
      'swipe',
      'type',
    ],
    primarySources: [
      'src/daemon/handlers/interaction.ts',
      'src/daemon/selectors.ts',
      'src/daemon/handlers/__tests__/interaction.test.ts',
    ],
    docs: [
      'website/docs/docs/commands.md',
      'website/docs/docs/selectors.md',
      'skills/agent-device/SKILL.md',
      'skills/agent-device/references/exploration.md',
    ],
  },
  {
    name: 'snapshot',
    commands: [
      'alert',
      'clipboard',
      'diff',
      'keyboard',
      'rotate',
      'screenshot',
      'settings',
      'snapshot',
      'trigger-app-event',
      'wait',
    ],
    primarySources: [
      'src/daemon/handlers/snapshot.ts',
      'src/daemon/snapshot-processing.ts',
      'src/daemon/handlers/__tests__/snapshot-handler.test.ts',
    ],
    docs: [
      'website/docs/docs/commands.md',
      'website/docs/docs/snapshots.md',
      'skills/agent-device/SKILL.md',
      'skills/agent-device/references/exploration.md',
      'skills/agent-device/references/debugging.md',
    ],
  },
  {
    name: 'find',
    commands: ['find'],
    primarySources: [
      'src/daemon/handlers/find.ts',
      'src/daemon/selectors.ts',
      'src/daemon/handlers/__tests__/find.test.ts',
    ],
    docs: [
      'website/docs/docs/commands.md',
      'website/docs/docs/selectors.md',
      'skills/agent-device/references/exploration.md',
    ],
  },
  {
    name: 'recordTrace',
    commands: ['record', 'trace'],
    primarySources: [
      'src/daemon/handlers/record-trace.ts',
      'src/platforms/ios/runner-client.ts',
      'src/daemon/handlers/__tests__/record-trace.test.ts',
    ],
    docs: ['website/docs/docs/commands.md', 'skills/agent-device/references/verification.md'],
  },
];

const ROUTES = [
  {
    task: 'Learn the CLI surface or flag schema',
    paths: ['src/utils/command-schema.ts', 'src/utils/args.ts', 'knowledge/index.md'],
  },
  {
    task: 'Trace session lifecycle and session-owned commands',
    paths: [
      'src/daemon/handlers/session.ts',
      'src/daemon/session-store.ts',
      'skills/agent-device/references/bootstrap-install.md',
    ],
  },
  {
    task: 'Trace selectors and element interactions',
    paths: [
      'src/daemon/handlers/interaction.ts',
      'src/daemon/selectors.ts',
      'skills/agent-device/references/exploration.md',
    ],
  },
  {
    task: 'Trace snapshot, wait, alerts, settings, or screenshot behavior',
    paths: [
      'src/daemon/handlers/snapshot.ts',
      'src/daemon/snapshot-processing.ts',
      'website/docs/docs/snapshots.md',
    ],
  },
  {
    task: 'Trace replay, test, record, and trace flows',
    paths: [
      'src/daemon/handlers/record-trace.ts',
      'src/daemon/handlers/session-replay.ts',
      'website/docs/docs/replay-e2e.md',
    ],
  },
  {
    task: 'Trace Apple runner behavior',
    paths: [
      'src/platforms/ios/runner-contract.ts',
      'src/platforms/ios/runner-client.ts',
      'src/platforms/ios/runner-transport.ts',
    ],
  },
];

const SESSION_REQUIREMENTS = {
  noSessionRequired: new Set([
    'apps',
    'boot',
    'devices',
    'ensure-simulator',
    'install',
    'install-from-source',
    'metro',
    'open',
    'reinstall',
    'session',
  ]),
  managesOwnSessions: new Set(['batch', 'replay', 'test']),
};

function normalizeText(value) {
  return value.replace(/\r\n/g, '\n');
}

function compareStrings(a, b) {
  return a.localeCompare(b, 'en');
}

function getFlagMetadataByKey() {
  const byKey = new Map();
  for (const definition of getFlagDefinitions()) {
    const list = byKey.get(definition.key);
    if (list) list.push(definition);
    else byKey.set(definition.key, [definition]);
  }
  return byKey;
}

function buildFamilyDefinitionMap() {
  const commandToFamily = new Map();
  for (const family of FAMILY_DEFINITIONS) {
    for (const command of family.commands) {
      const existing = commandToFamily.get(command);
      if (existing) {
        throw new Error(`Command ${command} is assigned to multiple knowledge families.`);
      }
      commandToFamily.set(command, family);
    }
  }
  return commandToFamily;
}

function getSessionRequirement(command) {
  if (SESSION_REQUIREMENTS.noSessionRequired.has(command)) {
    return 'Does not require an active session.';
  }
  if (SESSION_REQUIREMENTS.managesOwnSessions.has(command)) {
    return 'Creates or manages sessions internally.';
  }
  if (command === 'close') {
    return 'Requires an active session to close it.';
  }
  return 'Usually expects an active session.';
}

function buildPlatformSupport(command, capabilityCommands) {
  if (!capabilityCommands.has(command)) return null;
  return Object.fromEntries(
    SAMPLE_DEVICES.map((sample) => [
      sample.key,
      isCommandSupportedOnDevice(command, sample.device),
    ]),
  );
}

function formatBool(value) {
  return value ? 'Yes' : 'No';
}

function formatLink(fromPath, targetPath) {
  const relative = path.relative(path.dirname(fromPath), path.join(ROOT_DIR, targetPath));
  return `[${targetPath}](${relative.split(path.sep).join('/')})`;
}

function formatListSection(fromPath, title, entries) {
  if (entries.length === 0) return `## ${title}\n\n- None`;
  return `## ${title}\n\n${entries.map((entry) => `- ${formatLink(fromPath, entry)}`).join('\n')}`;
}

function buildCommandManifest() {
  const flagMetadataByKey = getFlagMetadataByKey();
  const capabilityCommands = new Set(getSchemaCapabilityKeys());
  const familyDefinitionByCommand = buildFamilyDefinitionMap();
  return getCliCommandNames()
    .sort(compareStrings)
    .map((command) => {
      const schema = getCommandSchema(command);
      if (!schema) throw new Error(`Missing schema for command ${command}`);
      const family = familyDefinitionByCommand.get(command) ?? null;
      const allowedFlags = schema.allowedFlags.flatMap((key) => {
        return (flagMetadataByKey.get(key) ?? []).map((definition) => ({
          key: definition.key,
          names: [...definition.names],
          usageDescription: definition.usageDescription ?? '',
          usageLabel: definition.usageLabel ?? definition.names[0],
        }));
      });
      return {
        aliases: COMMAND_ALIASES[command] ?? [],
        allowedFlags,
        capabilityChecked: capabilityCommands.has(command),
        docs: family?.docs ?? ['website/docs/docs/commands.md'],
        family: family?.name ?? 'unclassified',
        helpDescription: schema.helpDescription,
        name: command,
        notes: COMMAND_NOTES[command] ?? [],
        paths: family?.primarySources ?? [],
        platformSupport: buildPlatformSupport(command, capabilityCommands),
        positionals: [...schema.positionalArgs],
        sessionRequirement: getSessionRequirement(command),
        summary: schema.summary ?? schema.helpDescription,
        usage:
          buildCommandUsageText(command)
            ?.split('\n', 1)[0]
            .replace(/^agent-device\s+/, '') ?? command,
      };
    });
}

function renderCommandPage(command) {
  const filePath = path.join(KNOWLEDGE_DIR, 'commands', `${command.name}.md`);
  const aliasBlock =
    command.aliases.length > 0
      ? command.aliases.map((alias) => `- \`${alias}\``).join('\n')
      : '- None';
  const notesBlock =
    command.notes.length > 0 ? command.notes.map((note) => `- ${note}`).join('\n') : '- None';
  const flagsBlock =
    command.allowedFlags.length > 0
      ? command.allowedFlags
          .map((flag) => `- \`${flag.usageLabel}\`: ${flag.usageDescription}`)
          .join('\n')
      : '- None';

  const platformBlock =
    command.platformSupport === null
      ? '_Capability checks are not defined for this command in `command-schema.ts`._'
      : [
          '| Target | Supported |',
          '| --- | --- |',
          ...SAMPLE_DEVICES.map(
            (sample) => `| ${sample.label} | ${formatBool(command.platformSupport[sample.key])} |`,
          ),
        ].join('\n');

  const sections = [
    GENERATED_HEADER,
    '',
    `# ${command.name}`,
    '',
    command.summary,
    '',
    '## Usage',
    '',
    '```bash',
    `agent-device ${command.usage}`,
    '```',
    '',
    '## Session Requirement',
    '',
    command.sessionRequirement,
    '',
    '## Aliases',
    '',
    aliasBlock,
    '',
    '## Notes',
    '',
    notesBlock,
    '',
    '## Allowed Flags',
    '',
    flagsBlock,
    '',
    '## Platform Coverage',
    '',
    platformBlock,
    '',
    formatListSection(filePath, 'Primary Source Paths', command.paths),
    '',
    formatListSection(filePath, 'Docs And Skills', command.docs),
  ];
  return `${sections.join('\n')}\n`;
}

function renderIndex(commands) {
  const filePath = path.join(KNOWLEDGE_DIR, 'index.md');
  const commandLines = commands
    .map(
      (command) =>
        `| \`${command.name}\` | ${command.summary} | [page](./commands/${command.name}.md) |`,
    )
    .join('\n');
  const sourceLinks = [
    'AGENTS.md',
    'src/utils/command-schema.ts',
    'src/core/capabilities.ts',
    'skills/agent-device/SKILL.md',
    'website/docs/docs/commands.md',
  ]
    .map((entry) => `- ${formatLink(filePath, entry)}`)
    .join('\n');

  return `${GENERATED_HEADER}

# Knowledge Index

This directory is the generated agent-facing map of the repo. The source of truth stays in code, docs, and skills; \`pnpm kb:build\` compiles that material into a cheaper starting point for exploration and drift checks.

## Primary Sources

${sourceLinks}

## Refresh Workflow

1. Run \`pnpm kb:build\` after changing command schema, capabilities, docs, or skills.
2. Run \`pnpm kb:check\` in CI or before merging to catch stale generated files.
3. Start investigation here, then jump to the linked source files for the owning command family.

## Command Index

| Command | Summary | Page |
| --- | --- | --- |
${commandLines}
`;
}

function renderPlatformMatrix(commands) {
  const rows = commands
    .map((command) => {
      if (command.platformSupport === null) {
        return `| \`${command.name}\` | n/a | n/a | n/a | n/a | n/a | n/a | n/a |`;
      }
      return (
        [
          `| \`${command.name}\``,
          formatBool(command.platformSupport.iosSimulator),
          formatBool(command.platformSupport.iosDevice),
          formatBool(command.platformSupport.tvSimulator),
          formatBool(command.platformSupport.macosDesktop),
          formatBool(command.platformSupport.androidEmulator),
          formatBool(command.platformSupport.androidDevice),
          formatBool(command.platformSupport.androidTv),
        ].join(' | ') + ' |'
      );
    })
    .join('\n');

  return `${GENERATED_HEADER}

# Platform Matrix

Generated from \`src/core/capabilities.ts\` by evaluating each command against a small set of representative device targets.

| Command | iOS sim | iOS device | tvOS sim | macOS | Android emu | Android device | Android TV |
| --- | --- | --- | --- | --- | --- | --- | --- |
${rows}
`;
}

function renderAgentRoutes() {
  const filePath = path.join(KNOWLEDGE_DIR, 'agent-routes.md');
  const sections = ROUTES.map((route) => {
    const paths = route.paths.map((entry) => `- ${formatLink(filePath, entry)}`).join('\n');
    return `## ${route.task}\n\n${paths}`;
  }).join('\n\n');

  return `${GENERATED_HEADER}

# Agent Routes

Use this page when deciding where to read first. The goal is to keep the first hop narrow and close to the owning module.

${sections}
`;
}

function renderIndexJson(commands) {
  return `${JSON.stringify(
    {
      generatedBy: 'pnpm kb:build',
      routes: ROUTES,
      sampleTargets: SAMPLE_DEVICES.map((sample) => ({
        key: sample.key,
        label: sample.label,
      })),
      sourceFiles: [
        'AGENTS.md',
        'src/utils/command-schema.ts',
        'src/core/capabilities.ts',
        'skills/agent-device/SKILL.md',
        'website/docs/docs/commands.md',
      ],
      commands,
    },
    null,
    2,
  )}\n`;
}

export async function buildKnowledgeFiles() {
  const commands = buildCommandManifest();
  const files = new Map();
  files.set('knowledge/index.md', renderIndex(commands));
  files.set('knowledge/platform-matrix.md', renderPlatformMatrix(commands));
  files.set('knowledge/agent-routes.md', renderAgentRoutes());
  files.set('knowledge/index.json', renderIndexJson(commands));
  for (const command of commands) {
    files.set(`knowledge/commands/${command.name}.md`, renderCommandPage(command));
  }

  const expectedPaths = new Set(
    [...files.keys()].map((relativePath) => path.join(ROOT_DIR, relativePath)),
  );
  for (const [relativePath] of files) {
    if (relativePath.endsWith('.md')) {
      const fullPath = path.join(ROOT_DIR, relativePath);
      const links = [...normalizeText(files.get(relativePath)).matchAll(/\]\(([^)]+)\)/g)].map(
        (match) => match[1],
      );
      for (const link of links) {
        if (link.startsWith('./') || link.startsWith('../')) {
          const resolved = path.resolve(path.dirname(fullPath), link);
          if (expectedPaths.has(resolved)) continue;
          await fs.access(resolved);
        }
      }
    }
  }
  return files;
}

export async function writeKnowledgeFiles(files) {
  await fs.rm(KNOWLEDGE_DIR, { force: true, recursive: true });
  for (const [relativePath, content] of files) {
    const outputPath = path.join(ROOT_DIR, relativePath);
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, normalizeText(content), 'utf8');
  }
}

async function listKnowledgeFiles() {
  const files = [];
  async function walk(currentDir) {
    const entries = await fs.readdir(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        await walk(fullPath);
        continue;
      }
      files.push(path.relative(ROOT_DIR, fullPath).split(path.sep).join('/'));
    }
  }

  try {
    await walk(KNOWLEDGE_DIR);
  } catch (error) {
    if (error && error.code === 'ENOENT') return [];
    throw error;
  }
  return files.sort(compareStrings);
}

export async function checkKnowledgeFiles(files) {
  const expectedPaths = [...files.keys()].sort(compareStrings);
  const actualPaths = await listKnowledgeFiles();
  const missing = expectedPaths.filter((entry) => !actualPaths.includes(entry));
  const extra = actualPaths.filter((entry) => !expectedPaths.includes(entry));
  const changed = [];

  for (const relativePath of expectedPaths) {
    const fullPath = path.join(ROOT_DIR, relativePath);
    let current = null;
    try {
      current = await fs.readFile(fullPath, 'utf8');
    } catch (error) {
      if (error && error.code === 'ENOENT') continue;
      throw error;
    }
    if (current !== null && normalizeText(current) !== normalizeText(files.get(relativePath))) {
      changed.push(relativePath);
    }
  }

  return {
    changed,
    extra,
    missing,
    ok: changed.length === 0 && extra.length === 0 && missing.length === 0,
  };
}
