export {
  assertBackendCapabilityAllowed,
  createAgentDevice,
  createMemorySessionStore,
  localCommandPolicy,
  restrictedCommandPolicy,
} from './runtime.ts';
export { createAgentDeviceClient } from './client.ts';
export { createLocalArtifactAdapter } from './io.ts';
export { commandCatalog, commands, createCommandRouter, ref, selector } from './commands/index.ts';
export { AppError, isAgentDeviceError, normalizeAgentDeviceError } from './utils/errors.ts';
export { centerOfRect } from './utils/snapshot.ts';

export type {
  AgentDevice,
  AgentDeviceRuntime,
  AgentDeviceRuntimeConfig,
  CommandClock,
  CommandContext,
  CommandPolicy,
  CommandSessionRecord,
  CommandSessionStore,
  DiagnosticsSink,
} from './runtime.ts';

export type {
  AgentDeviceBackend,
  AgentDeviceBackendPlatform,
  BackendActionResult,
  BackendAlertAction,
  BackendAlertInfo,
  BackendAlertResult,
  BackendAppEvent,
  BackendAppInfo,
  BackendAppListFilter,
  BackendAppState,
  BackendBackOptions,
  BackendCapabilityName,
  BackendCapabilitySet,
  BackendClipboardTextResult,
  BackendCommandContext,
  BackendDeviceOrientation,
  BackendEscapeHatches,
  BackendFillOptions,
  BackendInstallTarget,
  BackendFindTextResult,
  BackendKeyboardOptions,
  BackendKeyboardResult,
  BackendLongPressOptions,
  BackendOpenOptions,
  BackendOpenTarget,
  BackendPinchOptions,
  BackendPushInput,
  BackendReadTextResult,
  BackendRunnerCommand,
  BackendScrollOptions,
  BackendScrollTarget,
  BackendSnapshotAnalysis,
  BackendSnapshotFreshness,
  BackendSnapshotOptions,
  BackendScreenshotOptions,
  BackendScreenshotResult,
  BackendShellResult,
  BackendSnapshotResult,
  BackendSwipeOptions,
  BackendTapOptions,
} from './backend.ts';

export type {
  ArtifactAdapter,
  ArtifactDescriptor,
  CreateTempFileOptions,
  FileInputRef,
  FileOutputRef,
  LocalArtifactAdapterOptions,
  OutputVisibility,
  ReserveOutputOptions,
  ReservedOutputFile,
  ResolveInputOptions,
  ResolvedInputFile,
  TemporaryFile,
} from './io.ts';

export type {
  BoundAgentDeviceCommands,
  BoundRuntimeCommand,
  AppPushInput,
  CommandCatalogEntry,
  CommandResult,
  CommandRouter,
  CommandRouterConfig,
  CommandRouterRequest,
  CommandRouterResponse,
  CommandRouterResult,
  CloseAppCommandOptions,
  CloseAppCommandResult,
  GetAppStateCommandOptions,
  GetAppStateCommandResult,
  ListAppsCommandOptions,
  ListAppsCommandResult,
  OpenAppCommandOptions,
  OpenAppCommandResult,
  PushAppCommandOptions,
  PushAppCommandResult,
  RuntimeCommand,
  SelectorSnapshotOptions,
  TriggerAppEventCommandOptions,
  TriggerAppEventCommandResult,
  TypeTextCommandOptions,
  TypeTextCommandResult,
} from './commands/index.ts';

export type { AppErrorCode, NormalizedError } from './utils/errors.ts';

export type {
  AgentDeviceClient,
  AgentDeviceClientConfig,
  AgentDeviceCommandClient,
  AgentDeviceDaemonTransport,
  AgentDeviceDevice,
  AgentDeviceIdentifiers,
  AgentDeviceRequestOverrides,
  AgentDeviceSelectionOptions,
  AgentDeviceSession,
  AgentDeviceSessionDevice,
  AlertCommandOptions,
  AlertCommandResult,
  AppCloseOptions,
  AppCloseResult,
  AppDeployOptions,
  AppDeployResult,
  AppInstallFromSourceOptions,
  AppInstallFromSourceResult,
  AppListOptions,
  AppOpenOptions,
  AppOpenResult,
  AppPushOptions,
  AppStateCommandOptions,
  AppStateCommandResult,
  AppSwitcherCommandOptions,
  AppSwitcherCommandResult,
  AppTriggerEventOptions,
  BackCommandOptions,
  BackCommandResult,
  BatchRunOptions,
  BatchStep,
  CaptureDiffOptions,
  CaptureScreenshotOptions,
  CaptureScreenshotResult,
  CaptureSnapshotOptions,
  CaptureSnapshotResult,
  ClickOptions,
  ClipboardCommandOptions,
  ClipboardCommandResult,
  CommandRequestResult,
  DeviceBootOptions,
  ElementTarget,
  EnsureSimulatorOptions,
  EnsureSimulatorResult,
  FillOptions,
  FindLocator,
  FindOptions,
  FocusOptions,
  GetOptions,
  HomeCommandOptions,
  HomeCommandResult,
  InteractionTarget,
  IsOptions,
  KeyboardCommandOptions,
  KeyboardCommandResult,
  LogsOptions,
  LongPressOptions,
  MaterializationReleaseOptions,
  MaterializationReleaseResult,
  MetroPrepareOptions,
  MetroPrepareResult,
  NetworkOptions,
  PerfOptions,
  PermissionTarget,
  PinchOptions,
  PressOptions,
  RecordOptions,
  ReplayRunOptions,
  ReplayTestOptions,
  RotateCommandOptions,
  RotateCommandResult,
  ScrollOptions,
  SessionCloseResult,
  SettingsUpdateOptions,
  StartupPerfSample,
  SwipeOptions,
  TraceOptions,
  TypeTextOptions,
  WaitCommandOptions,
  WaitCommandResult,
} from './client.ts';

export type {
  Point,
  Rect,
  ScreenshotOverlayRef,
  SnapshotNode,
  SnapshotVisibility,
  SnapshotVisibilityReason,
} from './utils/snapshot.ts';
