export { createAgentDeviceClient } from './client.ts';
export { AppError } from './utils/errors.ts';
export { centerOfRect } from './utils/snapshot.ts';

export type {
  AgentDeviceClient,
  AgentDeviceClientConfig,
  AgentDeviceCommandClient,
  AgentDeviceDaemonTransport,
  AgentDeviceDevice,
  AgentDeviceIdentifiers,
  AgentDeviceRequestOverrides,
  AgentDeviceSelectionOptions,
  AgentDeviceSession,
  AgentDeviceSessionDevice,
  AlertCommandOptions,
  AlertCommandResult,
  AppCloseOptions,
  AppCloseResult,
  AppDeployOptions,
  AppDeployResult,
  AppInstallFromSourceOptions,
  AppInstallFromSourceResult,
  AppListOptions,
  AppOpenOptions,
  AppOpenResult,
  AppPushOptions,
  AppStateCommandOptions,
  AppStateCommandResult,
  AppSwitcherCommandOptions,
  AppSwitcherCommandResult,
  AppTriggerEventOptions,
  BackCommandOptions,
  BackCommandResult,
  BatchRunOptions,
  BatchStep,
  CaptureDiffOptions,
  CaptureScreenshotOptions,
  CaptureScreenshotResult,
  CaptureSnapshotOptions,
  CaptureSnapshotResult,
  ClickOptions,
  ClipboardCommandOptions,
  ClipboardCommandResult,
  CommandRequestResult,
  DeviceBootOptions,
  ElementTarget,
  EnsureSimulatorOptions,
  EnsureSimulatorResult,
  FillOptions,
  FindLocator,
  FindOptions,
  FocusOptions,
  GetOptions,
  HomeCommandOptions,
  HomeCommandResult,
  InteractionTarget,
  IsOptions,
  KeyboardCommandOptions,
  KeyboardCommandResult,
  LogsOptions,
  LongPressOptions,
  MaterializationReleaseOptions,
  MaterializationReleaseResult,
  MetroPrepareOptions,
  MetroPrepareResult,
  NetworkOptions,
  PerfOptions,
  PermissionTarget,
  PinchOptions,
  PressOptions,
  RecordOptions,
  ReplayRunOptions,
  ReplayTestOptions,
  RotateCommandOptions,
  RotateCommandResult,
  ScrollIntoViewOptions,
  ScrollOptions,
  SessionCloseResult,
  SettingsUpdateOptions,
  StartupPerfSample,
  SwipeOptions,
  TraceOptions,
  TypeTextOptions,
  WaitCommandOptions,
  WaitCommandResult,
} from './client.ts';

export type {
  Point,
  Rect,
  ScreenshotOverlayRef,
  SnapshotNode,
  SnapshotVisibility,
  SnapshotVisibilityReason,
} from './utils/snapshot.ts';
